### ISSUE TITLE
ANGULAR: Conflicts after upgrading to v4.4.1

### ISSUE THREAD

**Issue by gongAll** [fullcalendar/fullcalendar#5464]
```
    ERROR in node_modules/@fullcalendar/angular/node_modules/@fullcalendar/core/main.d.ts:5:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: version, OptionsInput, EventInput, EventDef, EventDefHash, EventInstance, EventInstanceHash, parseEventDef, createEventInstance, EventTuple, BusinessHoursInput, parseBusinessHours, applyAll, debounce, padStart, isInt, capitaliseFirstLetter, parseFieldSpecs, compareByFieldSpecs, compareByFieldSpec, flexibleCompare, computeVisibleDayRange, refineProps, matchCellWidths, uncompensateScroll, compensateScroll, subtractInnerElHeight, isMultiDayRange, distributeHeight, undistributeHeight, preventSelection, allowSelection, preventContextMenu, allowContextMenu, compareNumbers, enableCursor, disableCursor, diffDates, htmlEscape, cssToStr, removeExact, isArraysEqual, memoize, memoizeOutput, memoizeRendering, MemoizedRendering, intersectRects, Rect, pointInsideRect, constrainPoint, getRectCenter, diffPoints, Point, translateRect, mapHash, filterHash, isPropsEqual, findElements, findChildren, htmlToElement, createElement, insertAfterElement, prependToElement, removeElement, appendToElement, applyStyle, applyStyleProp, elementMatches, elementClosest, forceClassName, EventStore, filterEventStoreDefs, createEmptyEventStore, mergeEventStores, getRelevantEvents, eventTupleToStore, EventUiHash, EventUi, processScopedUiProps, combineEventUis, Splitter, SplittableProps, buildGotoAnchorHtml, getAllDayHtml, getDayClasses, preventDefault, listenBySelector, whenTransitionDone, computeInnerRect, computeEdges, computeHeightAndMargins, getClippingParents, computeClippingRect, computeRect, unpromisify, EmitterMixin, EmitterInterface, DateRange, rangeContainsMarker, intersectRanges, rangesEqual, rangesIntersect, rangeContainsRange, Mixin, PositionCache, ScrollComponent, ScrollbarWidths, ScrollController, ElementScrollController, WindowScrollController, Theme, Component, ComponentContext, DateComponent, Seg, EventSegUiInteractionState, Calendar, DatePointTransform, DateSpanTransform, DateSelectionApi, View, ViewProps, FgEventRenderer, buildSegCompareObj, FillRenderer, DateProfileGenerator, DateProfile, ViewDef, ViewSpec, DateSpan, DateSpanApi, DatePointApi, isDateSpansEqual, DateMarker, addDays, startOfDay, addMs, addWeeks, diffWeeks, diffWholeWeeks, diffWholeDays, diffDayAndTime, diffDays, isValidDate, Duration, createDuration, isSingleDay, multiplyDuration, addDurations, asRoughMinutes, asRoughSeconds, asRoughMs, wholeDivideDurations, greatestDurationDenominator, DateEnv, DateMarkerMeta, DateFormatter, createFormatter, VerboseFormattingArg, formatIsoTimeString, NamedTimeZoneImpl, parseMarker, EventSourceDef, EventSource, EventSourceHash, Interaction, InteractionSettings, interactionSettingsToStore, interactionSettingsStore, InteractionSettingsStore, PointerDragEvent, Hit, dateSelectionJoinTransformer, eventDragMutationMassager, EventDropTransformers, EventResizeJoinTransforms, ElementDragging, formatDate, formatRange, globalDefaults, config, RecurringType, ParsedRecurring, DragMetaInput, DragMeta, parseDragMeta, createPlugin, PluginDef, PluginDefInput, ViewPropsTransformer, ViewContainerModifier, reducerFunc, Action, CalendarState, CalendarComponentProps, DayHeader, computeFallbackHeaderFormat, renderDateCell, DaySeries, EventInteractionState, EventRenderRange, sliceEventStore, hasBgRendering, getElSeg, computeEventDraggable, computeEventStartResizable, computeEventEndResizable, DayTable, DayTableSeg, DayTableCell, Slicer, SlicedProps, EventMutation, applyMutationToEventStore, Constraint, ConstraintInput, AllowFunc, isPropsValid, isInteractionValid, EventApi, requestJson, EventHandlerName, EventHandlerArgs, EventHandlerArg, EventRenderingChoice, NON_DATE_PROPS, DATE_PROPS, eventDefParserFunc, GenericHash, ClassNameInput, ElementContent, UNSCOPED_EVENT_UI_PROPS, default, ThemeClass, EqualityFuncHash, DateComponentHash, CalendarInteraction, CalendarInteractionClass, OptionChangeHandler, OptionChangeHandlerMap, ViewDefHash, ViewSpecHash, DAY_IDS, DurationInput, DateInput, FormatterInput, NamedTimeZoneImplClass, EventSourceError, EventInputTransformer, EventSourceSuccessResponseHandler, EventSourceErrorResponseHandler, EventSourceInput, EventSourceFetcher, InteractionClass, eventIsDraggableTransformer, ElementDraggingClass, rtlDefaults, ViewPropsTransformerClass, PluginSystem, CalendarComponent, eventDefMutationApplier, OverlapFunc, isPropsValidTester, LocaleCodeArg, LocaleSingularArg, RawLocaleMap, OptionsManager, EventSourceApi, ViewClass, ViewConfigInput, ViewConfigInputHash, ViewConfigHash, CmdFormatterFunc, CmdFormatter, FuncFormatterFunc, FuncFormatter, EventSourceFunc, _default, ExternalDefTransform, Toolbar
    
    5 declare module '@fullcalendar/core' {
      ~~~~~~~
    
      node_modules/@fullcalendar/core/main.d.ts:5:1
        5 declare module '@fullcalendar/core' {
          ~~~~~~~
        Conflicts are in this file.
    node_modules/@fullcalendar/core/main.d.ts:5:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: version, OptionsInput, EventInput, EventDef, EventDefHash, EventInstance, EventInstanceHash, parseEventDef, createEventInstance, EventTuple, BusinessHoursInput, parseBusinessHours, applyAll, debounce, padStart, isInt, capitaliseFirstLetter, parseFieldSpecs, compareByFieldSpecs, compareByFieldSpec, flexibleCompare, computeVisibleDayRange, refineProps, matchCellWidths, uncompensateScroll, compensateScroll, subtractInnerElHeight, isMultiDayRange, distributeHeight, undistributeHeight, preventSelection, allowSelection, preventContextMenu, allowContextMenu, compareNumbers, enableCursor, disableCursor, diffDates, htmlEscape, cssToStr, removeExact, isArraysEqual, memoize, memoizeOutput, memoizeRendering, MemoizedRendering, intersectRects, Rect, pointInsideRect, constrainPoint, getRectCenter, diffPoints, Point, translateRect, mapHash, filterHash, isPropsEqual, findElements, findChildren, htmlToElement, createElement, insertAfterElement, prependToElement, removeElement, appendToElement, applyStyle, applyStyleProp, elementMatches, elementClosest, forceClassName, EventStore, filterEventStoreDefs, createEmptyEventStore, mergeEventStores, getRelevantEvents, eventTupleToStore, EventUiHash, EventUi, processScopedUiProps, combineEventUis, Splitter, SplittableProps, buildGotoAnchorHtml, getAllDayHtml, getDayClasses, preventDefault, listenBySelector, whenTransitionDone, computeInnerRect, computeEdges, computeHeightAndMargins, getClippingParents, computeClippingRect, computeRect, unpromisify, EmitterMixin, EmitterInterface, DateRange, rangeContainsMarker, intersectRanges, rangesEqual, rangesIntersect, rangeContainsRange, Mixin, PositionCache, ScrollComponent, ScrollbarWidths, ScrollController, ElementScrollController, WindowScrollController, Theme, Component, ComponentContext, DateComponent, Seg, EventSegUiInteractionState, Calendar, DatePointTransform, DateSpanTransform, DateSelectionApi, View, ViewProps, FgEventRenderer, buildSegCompareObj, FillRenderer, DateProfileGenerator, DateProfile, ViewDef, ViewSpec, DateSpan, DateSpanApi, DatePointApi, isDateSpansEqual, DateMarker, addDays, startOfDay, addMs, addWeeks, diffWeeks, diffWholeWeeks, diffWholeDays, diffDayAndTime, diffDays, isValidDate, Duration, createDuration, isSingleDay, multiplyDuration, addDurations, asRoughMinutes, asRoughSeconds, asRoughMs, wholeDivideDurations, greatestDurationDenominator, DateEnv, DateMarkerMeta, DateFormatter, createFormatter, VerboseFormattingArg, formatIsoTimeString, NamedTimeZoneImpl, parseMarker, EventSourceDef, EventSource, EventSourceHash, Interaction, InteractionSettings, interactionSettingsToStore, interactionSettingsStore, InteractionSettingsStore, PointerDragEvent, Hit, dateSelectionJoinTransformer, eventDragMutationMassager, EventDropTransformers, EventResizeJoinTransforms, ElementDragging, formatDate, formatRange, globalDefaults, config, RecurringType, ParsedRecurring, DragMetaInput, DragMeta, parseDragMeta, createPlugin, PluginDef, PluginDefInput, ViewPropsTransformer, ViewContainerModifier, reducerFunc, Action, CalendarState, CalendarComponentProps, DayHeader, computeFallbackHeaderFormat, renderDateCell, DaySeries, EventInteractionState, EventRenderRange, sliceEventStore, hasBgRendering, getElSeg, computeEventDraggable, computeEventStartResizable, computeEventEndResizable, DayTable, DayTableSeg, DayTableCell, Slicer, SlicedProps, EventMutation, applyMutationToEventStore, Constraint, ConstraintInput, AllowFunc, isPropsValid, isInteractionValid, EventApi, requestJson, EventHandlerName, EventHandlerArgs, EventHandlerArg, EventRenderingChoice, NON_DATE_PROPS, DATE_PROPS, eventDefParserFunc, GenericHash, ClassNameInput, ElementContent, UNSCOPED_EVENT_UI_PROPS, default, ThemeClass, EqualityFuncHash, DateComponentHash, CalendarInteraction, CalendarInteractionClass, OptionChangeHandler, OptionChangeHandlerMap, ViewDefHash, ViewSpecHash, DAY_IDS, DurationInput, DateInput, FormatterInput, NamedTimeZoneImplClass, EventSourceError, EventInputTransformer, EventSourceSuccessResponseHandler, EventSourceErrorResponseHandler, EventSourceInput, EventSourceFetcher, InteractionClass, eventIsDraggableTransformer, ElementDraggingClass, rtlDefaults, ViewPropsTransformerClass, PluginSystem, CalendarComponent, eventDefMutationApplier, OverlapFunc, isPropsValidTester, LocaleCodeArg, LocaleSingularArg, RawLocaleMap, OptionsManager, EventSourceApi, ViewClass, ViewConfigInput, ViewConfigInputHash, ViewConfigHash, CmdFormatterFunc, CmdFormatter, FuncFormatterFunc, FuncFormatter, EventSourceFunc, _default, ExternalDefTransform, Toolbar
    
    5 declare module '@fullcalendar/core' {
      ~~~~~~~
    
      node_modules/@fullcalendar/angular/node_modules/@fullcalendar/core/main.d.ts:5:1
        5 declare module '@fullcalendar/core' {
          ~~~~~~~
        Conflicts are in this file.
    node_modules/@fullcalendar/core/main.d.ts:115:9 - error TS2374: Duplicate string index signature.
    
    115         [viewId: string]: string | undefined;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@fullcalendar/core/main.d.ts:453:9 - error TS2374: Duplicate string index signature.
    
    453         [extendedProp: string]: any;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@fullcalendar/core/main.d.ts:1019:9 - error TS2374: Duplicate string index signature.
    
    1019         [otherProp: string]: any;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@fullcalendar/core/main.d.ts:1487:9 - error TS2374: Duplicate string index signature.
    
    1487         [otherProp: string]: any;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@fullcalendar/core/main.d.ts:1496:9 - error TS2374: Duplicate string index signature.
    
    1496         [otherProp: string]: any;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@fullcalendar/core/main.d.ts:1792:9 - error TS2374: Duplicate string index signature.
    
    1792         [otherProp: string]: any;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@fullcalendar/core/main.d.ts:2588:9 - error TS2374: Duplicate string index signature.
    
    2588         [otherProp: string]: any;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@fullcalendar/core/main.d.ts:2637:9 - error TS2374: Duplicate string index signature.
    
    2637         [optionName: string]: any;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@fullcalendar/daygrid/main.d.ts:5:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: SimpleDayGrid, DayGridSlicer, DayGrid, DayGridSeg, AbstractDayGridView, DayGridView, buildBasicDayTable, DayBgRow, _default, default, Popover, DayGridEventRenderer, DayTile, DayTileEventRenderer, SimpleDayGridEventRenderer
    
    5 declare module '@fullcalendar/daygrid' {
      ~~~~~~~
    
      node_modules/@fullcalendar/timegrid/node_modules/@fullcalendar/daygrid/main.d.ts:5:1
        5 declare module '@fullcalendar/daygrid' {
          ~~~~~~~
        Conflicts are in this file.
    node_modules/@fullcalendar/timegrid/node_modules/@fullcalendar/daygrid/main.d.ts:5:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: SimpleDayGrid, DayGridSlicer, DayGrid, DayGridSeg, AbstractDayGridView, DayGridView, buildBasicDayTable, DayBgRow, _default, default, Popover, DayGridEventRenderer, DayTile, DayTileEventRenderer, SimpleDayGridEventRenderer
    
    5 declare module '@fullcalendar/daygrid' {
      ~~~~~~~
    
      node_modules/@fullcalendar/daygrid/main.d.ts:5:1
        5 declare module '@fullcalendar/daygrid' {
          ~~~~~~~
        Conflicts are in this file.

```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue? Would really appreciate it because the time saved reproducing will be time spent fixing.

It sounds like maybe not all the modules were updated to the new version.

**Comment by gongAll** [comment]
Well that makes sense. All of them were updated on v4.4.1 except rrule, interaction and resource-timeline (which did not have the new version). However, now that it does on v4.4.2, I get the error of  incorrect peer dependency for "@angular/common@>=7.0.0 <9.0.0" and "@angular/core@>=7.0.0 <9.0.0" since I was using @fullcalendar/angular@4.4.5-beta which was created to support angular 9 environments.

```
ERROR in The target entry-point "@fullcalendar/angular" has missing dependencies:
 - @fullcalendar/core/types/input-types
 - @fullcalendar/core/datelib/env
 - @fullcalendar/core/datelib/duration
 - @fullcalendar/core/datelib/formatting
 - @fullcalendar/core/datelib/date-range
 - @fullcalendar/core/datelib/locale
 - @fullcalendar/core/validation
 - @fullcalendar/core/structs/event-source
```

This is the exact same error that happened to me after upgrading to angular 9 on fullcalendar version 4.4.0 and before updating @fullcalendar/angular to version 4.4.5-beta.

Could there be a fix for this? I believe you already have the changes necessary to fix this on v4.4.5-beta release. @acerix @arshaw

**Comment by acerix** [comment]
4.4.2 was releases to fix the problem of dependencies not getting updated which seem like your original issue.

I'm not sure how to reproduce the "missing dependencies" error though, when I try building the example project, I don't get any error and it uses Angular 9.0.2.  

https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular

**Comment by gongAll** [comment]
I believe it has something to do with the typescript version. On v4.4.5-beta it is on 3.7.x and on 4.4.2 it is on 3.2.x. We currently use typescript 3.9.x. However I will try to create a codepen for this tomorrow. 

But if you see the [diff ](https://github.com/fullcalendar/fullcalendar-angular/compare/v4.4.2...v4.4.5-beta)between v4.4.5-beta and v4.4.2 it seems to be fixing this exact problem by commenting the imports and defining them as types as a possibly temporary workaround.

**Comment by gongAll** [comment]
After further researching I do believe the fix from v4.4.5-beta must be applied to the v4.4.2 of @fullcalendar/angular module, as per @arshaw himself ([link](https://github.com/fullcalendar/fullcalendar-angular/issues/270#issuecomment-585528767)), so I think no replication is necessary. 

@acerix The test you did I believe was on v5 and not on v4, since the master branch (which is the v4 branch) of https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular is on angular@7.2.0 and only the v5 branch is on angular@9.0.2.

In terms of working versions it goes as follows:
**WORKS** -> angular at v4.4.5-beta and the other modules on v4.4.0;
**doesn't work** -> angular at v4.4.5-beta and the other modules on v4.4.2 (throws the error initially reported);
**doesn't work** -> all the modules on v4.4.2 (throws the "missing dependencies" error);

**Comment by acerix** [comment]
Sorry, yes, I was testing with the v5 branch by mistake. And thanks for the additional info, I believe the issue is that v4 is not compatible with Angular 9, there is an open issue in that repo:

https://github.com/fullcalendar/fullcalendar-angular/issues/291
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by gongAll** [comment]
Oh, ok I will upvote that issue. Thought it was supposed to eventually be compatible with angular v9 because of the v4.4.5-beta release. Thanks for the redirect to the correct issue.

**Comment by acerix** [comment]
I took a closer look and found that 4.4.5 is actually an older release from before Angular 9 support was added. The newest is 4.4.2 and that seems to be working with everything updated:

https://stackblitz.com/edit/github-avymb2?file=package.json
