### ISSUE TITLE
Many TypeScript issues after upgrading from 4.2.0 to 4.3.0

### ISSUE THREAD

**Issue by benneq** [fullcalendar/fullcalendar#4968]
I upgraded the following packages to `4.3.0`:
```
$ npm outdated
Package                         Current  
@fullcalendar/angular             4.2.1    
@fullcalendar/core                4.2.0     
@fullcalendar/daygrid             4.2.0   
@fullcalendar/interaction         4.2.0   
```

My environment:
```
TypeScript      3.5.3
NodeJs          10.6.2
Angular         8.2.1
```

I can reproduce the errors over and over again just by switching between fullcalendar `4.2.0` and `4.3.0`.

Here's the error output:
```
ERROR in node_modules/@fullcalendar/angular/node_modules/@fullcalendar/core/main.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: version, OptionsInput, EventInput, EventDef, EventDefHash, EventInstance, EventInstanceHash, parseEventDef, createEventInstance, EventTuple, BusinessHoursInput, parseBusinessHours, applyAll, debounce, padStart, isInt, capitaliseFirstLetter, parseFieldSpecs, compareByFieldSpecs, compareByFieldSpec, flexibleCompare, computeVisibleDayRange, refineProps, matchCellWidths, uncompensateScroll, compensateScroll, subtractInnerElHeight, isMultiDayRange, distributeHeight, undistributeHeight, preventSelection, allowSelection, preventContextMenu, allowContextMenu, compareNumbers, enableCursor, disableCursor, diffDates, htmlEscape, cssToStr, removeExact, isArraysEqual, memoize, memoizeOutput, memoizeRendering, MemoizedRendering, intersectRects, Rect, pointInsideRect, constrainPoint, getRectCenter, diffPoints, Point, translateRect, mapHash, filterHash, isPropsEqual, findElements, findChildren, htmlToElement, createElement, insertAfterElement, prependToElement, removeElement, appendToElement, applyStyle, applyStyleProp, elementMatches, elementClosest, forceClassName, EventStore, filterEventStoreDefs, createEmptyEventStore, mergeEventStores, getRelevantEvents, eventTupleToStore, EventUiHash, EventUi, processScopedUiProps, combineEventUis, Splitter, SplittableProps, buildGotoAnchorHtml, getAllDayHtml, getDayClasses, preventDefault, listenBySelector, whenTransitionDone, computeInnerRect, computeEdges, computeHeightAndMargins, getClippingParents, computeClippingRect, computeRect, unpromisify, EmitterMixin, EmitterInterface, DateRange, rangeContainsMarker, intersectRanges, rangesEqual, rangesIntersect, rangeContainsRange, Mixin, PositionCache, ScrollComponent, ScrollbarWidths, ScrollController, ElementScrollController, WindowScrollController, Theme, Component, ComponentContext, DateComponent, Seg, EventSegUiInteractionState, Calendar, DatePointTransform, DateSpanTransform, DateSelectionApi, View, ViewProps, FgEventRenderer, buildSegCompareObj, FillRenderer, DateProfileGenerator, DateProfile, ViewDef, ViewSpec, DateSpan, DateSpanApi, DatePointApi, isDateSpansEqual, DateMarker, addDays, startOfDay, addMs, addWeeks, diffWeeks, diffWholeWeeks, diffWholeDays, diffDayAndTime, diffDays, isValidDate, Duration, createDuration, isSingleDay, multiplyDuration, addDurations, asRoughMinutes, asRoughSeconds, asRoughMs, wholeDivideDurations, greatestDurationDenominator, DateEnv, DateMarkerMeta, DateFormatter, createFormatter, VerboseFormattingArg, formatIsoTimeString, NamedTimeZoneImpl, parseMarker, EventSourceDef, EventSource, EventSourceHash, Interaction, InteractionSettings, interactionSettingsToStore, interactionSettingsStore, InteractionSettingsStore, PointerDragEvent, Hit, dateSelectionJoinTransformer, eventDragMutationMassager, EventResizeJoinTransforms, ElementDragging, formatDate, formatRange, globalDefaults, config, RecurringType, ParsedRecurring, DragMetaInput, DragMeta, parseDragMeta, createPlugin, PluginDef, PluginDefInput, ViewPropsTransformer, ViewContainerModifier, reducerFunc, Action, CalendarState, CalendarComponentProps, DayHeader, computeFallbackHeaderFormat, renderDateCell, DaySeries, EventInteractionState, EventRenderRange, sliceEventStore, hasBgRendering, getElSeg, DayTable, DayTableSeg, DayTableCell, Slicer, SlicedProps, EventMutation, applyMutationToEventStore, Constraint, ConstraintInput, AllowFunc, isPropsValid, isInteractionValid, EventApi, requestJson, EventHandlerName, EventHandlerArgs, EventHandlerArg, EventRenderingChoice, NON_DATE_PROPS, DATE_PROPS, eventDefParserFunc, GenericHash, ClassNameInput, ElementContent, UNSCOPED_EVENT_UI_PROPS, default, ThemeClass, EqualityFuncHash, DateComponentHash, CalendarInteraction, CalendarInteractionClass, OptionChangeHandler, OptionChangeHandlerMap, ViewDefHash, ViewSpecHash, DAY_IDS, DurationInput, DateInput, FormatterInput, NamedTimeZoneImplClass, EventSourceError, EventInputTransformer, EventSourceSuccessResponseHandler, EventSourceErrorResponseHandler, EventSourceInput, EventSourceFetcher, InteractionClass, EventDropTransformers, ElementDraggingClass, rtlDefaults, ViewPropsTransformerClass, PluginSystem, CalendarComponent, eventDefMutationApplier, OverlapFunc, isPropsValidTester, LocaleCodeArg, LocaleSingularArg, RawLocaleMap, OptionsManager, EventSourceApi, ViewClass, ViewConfigInput, ViewConfigInputHash, ViewConfigHash, CmdFormatterFunc, CmdFormatter, FuncFormatterFunc, FuncFormatter, EventSourceFunc, _default, ExternalDefTransform, Toolbar

1 declare module "@fullcalendar/core/util/dom-manip" {
  ~~~~~~~

  node_modules/@fullcalendar/core/main.d.ts:5:1
    5 declare module '@fullcalendar/core' {
      ~~~~~~~
    Conflicts are in this file.
node_modules/@fullcalendar/core/main.d.ts:5:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: version, OptionsInput, EventInput, EventDef, EventDefHash, EventInstance, EventInstanceHash, parseEventDef, createEventInstance, EventTuple, BusinessHoursInput, parseBusinessHours, applyAll, debounce, padStart, isInt, capitaliseFirstLetter, parseFieldSpecs, compareByFieldSpecs, compareByFieldSpec, flexibleCompare, computeVisibleDayRange, refineProps, matchCellWidths, uncompensateScroll, compensateScroll, subtractInnerElHeight, isMultiDayRange, distributeHeight, undistributeHeight, preventSelection, allowSelection, preventContextMenu, allowContextMenu, compareNumbers, enableCursor, disableCursor, diffDates, htmlEscape, cssToStr, removeExact, isArraysEqual, memoize, memoizeOutput, memoizeRendering, MemoizedRendering, intersectRects, Rect, pointInsideRect, constrainPoint, getRectCenter, diffPoints, Point, translateRect, mapHash, filterHash, isPropsEqual, findElements, findChildren, htmlToElement, createElement, insertAfterElement, prependToElement, removeElement, appendToElement, applyStyle, applyStyleProp, elementMatches, elementClosest, forceClassName, EventStore, filterEventStoreDefs, createEmptyEventStore, mergeEventStores, getRelevantEvents, eventTupleToStore, EventUiHash, EventUi, processScopedUiProps, combineEventUis, Splitter, SplittableProps, buildGotoAnchorHtml, getAllDayHtml, getDayClasses, preventDefault, listenBySelector, whenTransitionDone, computeInnerRect, computeEdges, computeHeightAndMargins, getClippingParents, computeClippingRect, computeRect, unpromisify, EmitterMixin, EmitterInterface, DateRange, rangeContainsMarker, intersectRanges, rangesEqual, rangesIntersect, rangeContainsRange, Mixin, PositionCache, ScrollComponent, ScrollbarWidths, ScrollController, ElementScrollController, WindowScrollController, Theme, Component, ComponentContext, DateComponent, Seg, EventSegUiInteractionState, Calendar, DatePointTransform, DateSpanTransform, DateSelectionApi, View, ViewProps, FgEventRenderer, buildSegCompareObj, FillRenderer, DateProfileGenerator, DateProfile, ViewDef, ViewSpec, DateSpan, DateSpanApi, DatePointApi, isDateSpansEqual, DateMarker, addDays, startOfDay, addMs, addWeeks, diffWeeks, diffWholeWeeks, diffWholeDays, diffDayAndTime, diffDays, isValidDate, Duration, createDuration, isSingleDay, multiplyDuration, addDurations, asRoughMinutes, asRoughSeconds, asRoughMs, wholeDivideDurations, greatestDurationDenominator, DateEnv, DateMarkerMeta, DateFormatter, createFormatter, VerboseFormattingArg, formatIsoTimeString, NamedTimeZoneImpl, parseMarker, EventSourceDef, EventSource, EventSourceHash, Interaction, InteractionSettings, interactionSettingsToStore, interactionSettingsStore, InteractionSettingsStore, PointerDragEvent, Hit, dateSelectionJoinTransformer, eventDragMutationMassager, EventResizeJoinTransforms, ElementDragging, formatDate, formatRange, globalDefaults, config, RecurringType, ParsedRecurring, DragMetaInput, DragMeta, parseDragMeta, createPlugin, PluginDef, PluginDefInput, ViewPropsTransformer, ViewContainerModifier, reducerFunc, Action, CalendarState, CalendarComponentProps, DayHeader, computeFallbackHeaderFormat, renderDateCell, DaySeries, EventInteractionState, EventRenderRange, sliceEventStore, hasBgRendering, getElSeg, DayTable, DayTableSeg, DayTableCell, Slicer, SlicedProps, EventMutation, applyMutationToEventStore, Constraint, ConstraintInput, AllowFunc, isPropsValid, isInteractionValid, EventApi, requestJson, EventHandlerName, EventHandlerArgs, EventHandlerArg, EventRenderingChoice, NON_DATE_PROPS, DATE_PROPS, eventDefParserFunc, GenericHash, ClassNameInput, ElementContent, UNSCOPED_EVENT_UI_PROPS, default, ThemeClass, EqualityFuncHash, DateComponentHash, CalendarInteraction, CalendarInteractionClass, OptionChangeHandler, OptionChangeHandlerMap, ViewDefHash, ViewSpecHash, DAY_IDS, DurationInput, DateInput, FormatterInput, NamedTimeZoneImplClass, EventSourceError, EventInputTransformer, EventSourceSuccessResponseHandler, EventSourceErrorResponseHandler, EventSourceInput, EventSourceFetcher, InteractionClass, EventDropTransformers, ElementDraggingClass, rtlDefaults, ViewPropsTransformerClass, PluginSystem, CalendarComponent, eventDefMutationApplier, OverlapFunc, isPropsValidTester, LocaleCodeArg, LocaleSingularArg, RawLocaleMap, OptionsManager, EventSourceApi, ViewClass, ViewConfigInput, ViewConfigInputHash, ViewConfigHash, CmdFormatterFunc, CmdFormatter, FuncFormatterFunc, FuncFormatter, EventSourceFunc, _default, ExternalDefTransform, Toolbar

5 declare module '@fullcalendar/core' {
  ~~~~~~~

  node_modules/@fullcalendar/angular/node_modules/@fullcalendar/core/main.d.ts:1:1
    1 declare module "@fullcalendar/core/util/dom-manip" {
      ~~~~~~~
    Conflicts are in this file.
node_modules/@fullcalendar/core/main.d.ts:115:9 - error TS2374: Duplicate string index signature.

115         [viewId: string]: string | undefined;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@fullcalendar/core/main.d.ts:453:9 - error TS2374: Duplicate string index signature.

453         [extendedProp: string]: any;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@fullcalendar/core/main.d.ts:1014:9 - error TS2374: Duplicate string index signature.

1014         [otherProp: string]: any;
             ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@fullcalendar/core/main.d.ts:1494:9 - error TS2374: Duplicate string index signature.

1494         [otherProp: string]: any;
             ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@fullcalendar/core/main.d.ts:1503:9 - error TS2374: Duplicate string index signature.

1503         [otherProp: string]: any;
             ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@fullcalendar/core/main.d.ts:1799:9 - error TS2374: Duplicate string index signature.

1799         [otherProp: string]: any;
             ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@fullcalendar/core/main.d.ts:2580:9 - error TS2374: Duplicate string index signature.

2580         [otherProp: string]: any;
             ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@fullcalendar/core/main.d.ts:2631:9 - error TS2374: Duplicate string index signature.

2631         [optionName: string]: any;
             ~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@fullcalendar/daygrid/main.d.ts:166:9 - error TS2416: Property 'computeDateScroll' in type 'DayGridView' is not assignable to the same property in base type 'View'.
  Type '(duration: Duration) => { top: number; }' is not assignable to type '(timeMs: number) => {}'.
    Types of parameters 'duration' and 'timeMs' are incompatible.
      Type 'number' is not assignable to type 'Duration'.

166         computeDateScroll(duration: Duration): {
            ~~~~~~~~~~~~~~~~~


```

**Comment by arshaw** [comment]
@benneq can you try doing a fresh install of this: https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular ... and see if it works? Can you verify that it installed v4.3.x ?

I have suspicions that you have multiple version of these packages installed in your node_modules, causing conflicts. Also, can you run `npm ls @fullcalendar/core` in your repo to see what is using it?

**Comment by benneq** [comment]
Here's the result of `npm ls @fullcalendar/core` with `4.2.0` in my project:
```
frontend@0.0.1 /Users/benneq/Development/frontend
├─┬ @fullcalendar/angular@4.2.1
│ └── @fullcalendar/core@4.2.0  deduped
└── @fullcalendar/core@4.2.0 
```

Here's with `4.3.0`:
```
frontend@0.0.1 /Users/benneq/Development/frontend
├─┬ @fullcalendar/angular@4.3.0
│ └── @fullcalendar/core@4.2.0 
└── @fullcalendar/core@4.3.0
```

Why is there `core@4.2.0` in there?

---

I also downloaded the project from https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular
This is using fullcalendar `4.1.0` angular `7.2` and typescript `3.2`.

So I upgraded the whole `package.json` with my current versions:
```
  "dependencies": {
    "@angular/animations": "~8.2.1",
    "@angular/common": "~8.2.1",
    "@angular/compiler": "~8.2.1",
    "@angular/core": "~8.2.1",
    "@angular/forms": "~8.2.1",
    "@angular/platform-browser": "~8.2.1",
    "@angular/platform-browser-dynamic": "~8.2.1",
    "@angular/router": "~8.2.1",
    "@fullcalendar/angular": "^4.3.0",
    "@fullcalendar/core": "^4.3.0",
    "@fullcalendar/daygrid": "^4.3.0",
    "@fullcalendar/interaction": "^4.3.0",
    "@fullcalendar/timegrid": "^4.3.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.2",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.802.1",
    "@angular/cli": "~8.2.1",
    "@angular/compiler-cli": "~8.2.1",
    "@angular/language-service": "~8.2.1",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.4.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~5.1.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.5.3"
  }
```

Then did `rm -rf node_modules package-lock.json && npm i`. And then started the project using `npm start`. I get the same errors as with my project.

**Comment by benneq** [comment]
EDIT: I've now manually removed the `fullcalendar/core` dependency from `fullcalendar/angular` within `package-lock.json` and then did `rm -rf node_modules && npm i`.

Before:
```
    "@fullcalendar/angular": {
      "version": "4.3.0",
      "resolved": "https://registry.npmjs.org/@fullcalendar/angular/-/angular-4.3.0.tgz",
      "integrity": "sha512-aisEsg4ELJdSUh0ywTwItg/D/6NxSmLzmaxZWSCtE84sq4opUTItVh4SQHNEHFj3gKT7RAMqeiy5FofVnfdshw==",
      "requires": {
        "@fullcalendar/core": "~4.2.0",
        "fast-deep-equal": "^2.0.1",
        "tslib": "^1.9.0"
      },
      "dependencies": {
        "@fullcalendar/core": {
          "version": "4.2.0",
          "resolved": "https://registry.npmjs.org/@fullcalendar/core/-/core-4.2.0.tgz",
          "integrity": "sha512-4kd5OGHxjMtwI0gUHKwAYzmR0Z79Qf8y0ARx2Ruh20JdVy3Tznn6oKwdpkUbaXWrLXNDoXYRkBiFCIgC27VNCw=="
        }
      }
    },
```

After:
```
    "@fullcalendar/angular": {
      "version": "4.3.0",
      "resolved": "https://registry.npmjs.org/@fullcalendar/angular/-/angular-4.3.0.tgz",
      "integrity": "sha512-aisEsg4ELJdSUh0ywTwItg/D/6NxSmLzmaxZWSCtE84sq4opUTItVh4SQHNEHFj3gKT7RAMqeiy5FofVnfdshw==",
      "requires": {
        "fast-deep-equal": "^2.0.1",
        "tslib": "^1.9.0"
      }
    },
```

Now everything is working as expected. Maybe you should also remove the hard dependency. ❓

**Comment by arshaw** [comment]
Thanks for all the info. I've found the bug. For some reason @fullcalendar/angular 4.3.0 is requiring the 4.2.0 core which is not right: https://cdn.jsdelivr.net/npm/@fullcalendar/angular@4.3.0/package.json

will fix that asap

**Comment by arshaw** [comment]
I've published a new version of @fullcalendar/angular that fixes this problem. can you do a fresh install of all node_modules and see if its fixed?

**Comment by arshaw** [comment]
the new version is 4.3.1

**Comment by benneq** [comment]
I now installed version `4.3.1`:
```
    "@fullcalendar/angular": "^4.3.1",
    "@fullcalendar/core": "^4.3.1",
    "@fullcalendar/daygrid": "^4.3.0",
    "@fullcalendar/interaction": "^4.3.0",
```

Then did `rm -rf node_modules package-lock.json && npm i`. And it **works!**

Thank you!
