### ISSUE TITLE
npm dependencies package move to devDependencies

### ISSUE THREAD

**Issue by taoche** [fullcalendar/fullcalendar#3330]
in packages "jquery": ">=2.0.0" can install >3.0  on submodule of jQuery...  
if customer use webpack and 2.x version (or different version) of jQuery.. 
$.fn is different Object... so $().fullcalendar is not a functions

move the dependencies package to devDependencies can solve this problem

I hope you can solve this problem  thans!!!

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I know for a fact that jQuery 2 and 3 both work with FC 3.0. If you're having build system problems it's likely related to your Webkit setup.
