### ISSUE TITLE
ERROR in node_modules/@fullcalendar/core/main.d.ts(545,27): error TS1005: ',' expected.

### ISSUE THREAD

**Issue by Jai-Kumaresh** [fullcalendar/fullcalendar#4572]
I have error for @fullcalendar/core module in my angular6 project. Error is

```
ERROR in node_modules/@fullcalendar/core/main.d.ts(545,27): error TS1005: ',' expected.
node_modules/@fullcalendar/core/main.d.ts(1582,29): error TS1005: ',' expected.
node_modules/@fullcalendar/core/main.d.ts(1591,29): error TS1005: ',' expected.
node_modules/@fullcalendar/core/main.d.ts(1596,29): error TS1005: ',' expected.
```

Any one know that solution please tell me.

**Comment by irustm** [comment]
please reproduce the minimum project in stackblitz with this error

**Comment by philippe9** [comment]
Same issue here

typescript version (local) 2.5.3 
typescript version (global) 3.2.4 
    "@fullcalendar/core": "^4.0.1",
    "@fullcalendar/daygrid": "^4.0.1",
    "@fullcalendar/list": "^4.0.1",
    "@fullcalendar/timegrid": "^4.0.1",

Please help needed

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or the steps to reproduce? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by philippe9** [comment]
Thanks for the response, I think it is what I already done above .The only things installed above are angular basic requirements and fullcalendar but it still doesn't apprear and locally it gives the error
 
`ERROR in node_modules/@fullcalendar/core/main.d.ts(545,27): error TS1005: ',' expected.`

I also followed the steps of your link but the error continues
Here is the editor url of the above result https://stackblitz.com/edit/angular-1aegtn . Hope it helps.

**Comment by acerix** [comment]
Thanks, I didn't realize it was a runnable demo because the page just says "Hello Angular! Start editing to see some magic happen :)". Is there a way to see the error in stackblitz?

**Comment by philippe9** [comment]
For the CLI error, I don't know how is it possible with stackblitz if you have a tool than is better I am ready to use it.Thanks

**Comment by acerix** [comment]
I don't get any errors when building the TypeScript using the example project:

https://github.com/fullcalendar/typescript-example

It would help if you can provide something like that which is easy to run, or just the instructions/commands to reproduce the errors.

**Comment by irustm** [comment]
@philippe9  Don't use `document.addEventListener('DOMContentLoaded', ` in ngOnInit hook 
 and use typescript ^3.1.1.  I'am fork you repo, and fix it: https://stackblitz.com/edit/angular-rdlpeo?file=src/app/app.component.ts

---
Try use ng-fullcalendar@2.0.3 https://stackblitz.com/edit/ng-fullcalendar2-demo

**Comment by philippe9** [comment]
Thanks @irustm , the problem of `error TS1110: Type expected.` got solved when I upgraded my local typescript version to 3.1.1 and fullcalendar appeared fine when I used ng-fullcalendar (by the way I was not aware of the existance of an angular version). But now my CLI throws this warning

```
@angular/compiler-cli@5.2.11 requires typescript@'>=2.4.2 <2.7.0' but 3.1.1 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.7.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".
```

My project still works fine with the warning but if I have a problem on my way I will come towards you, thanks again and have a good day.

**Comment by irustm** [comment]
To solve this warning you can update your angular project to a later version, example angular 6 or ^7. 
Or disable warning `ng set warnings.typescriptMismatch=false`

**Comment by elizadoolittle** [comment]
I am also seeing this same issue, 
![image](https://user-images.githubusercontent.com/14101271/57552269-9825a200-7328-11e9-89cc-5d13ed216fed.png)

![image](https://user-images.githubusercontent.com/14101271/57552281-a4116400-7328-11e9-9bba-7bbcd1353b46.png)
![image](https://user-images.githubusercontent.com/14101271/57552295-ae336280-7328-11e9-90ae-20f433bea5a1.png)

I used instructions from: https://fullcalendar.io/docs/angular
![image](https://user-images.githubusercontent.com/14101271/57552320-c6a37d00-7328-11e9-8d4a-4e29e98cb450.png)


In order to replicate, you'd really just need to create a sample component, something really basic that simply imports the calendar. And install the NPM packages, and try and build.

**Comment by Sriramamoorthy** [comment]
Just updating fullcalendar packages to latest will solve the issue
