### ISSUE TITLE
Property 'type' does not exist on type 'ViewApi'

### ISSUE THREAD

**Issue by roelkoops** [fullcalendar/fullcalendar#7056]
### Reduced Test Case

not reproducible with a link

### Bug Description

After upgrading to v6.0.0 i get an error:  "Property 'type' does not exist on type 'ViewApi'".
According to the documentation (https://fullcalendar.io/docs/view-object) this property should still exist in v6.0.0, but it is missing in the interface:

```
interface ViewApi {
    calendar: CalendarApi;
    title: string;
    activeStart: Date;
    activeEnd: Date;
    currentStart: Date;
    currentEnd: Date;
    getOption(name: string): any;
}
```

**Comment by acerix** [comment]
I tested this in our Vue3 debug template and can confirm `type` seems to be missing now.  As a workaround, the type check can be ignored by casting to `any`:

![f](https://user-images.githubusercontent.com/379534/207737173-a44d639b-6635-4201-93a8-7affce8e5748.png)

https://stackblitz.com/edit/github-6g88fe?file=src%2FDemoApp.vue

Also reported in https://fullcalendar.freshdesk.com/a/tickets/5814

**Comment by arshaw** [comment]
Fixed released in [v6.0.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.1)
