### ISSUE TITLE
Angular/PrimeNG 4 + jQuery 3.5.1 + FullCalendar 3.10.2 is broken

### ISSUE THREAD

**Issue by neeohw** [fullcalendar/fullcalendar#5460]
We have a project on Angular 4/PrimeNG 4 with jQuery and fullcalendar 3
We had to put jQuery fixed on version 3.4.1 a few weeks ago, because fullcalendar 3 was not compatible.
Now we saw that fullCalendar was "fixed", but it doesn't seem to work in combination with PrimeNG 4
It seems it's not compatible with p-schedule anymore.

Version 

AssignComponent.html:115 ERROR TypeError: this.schedule.fullCalendar is not a function
    at Schedule.webpackJsonp.../../../../primeng/components/schedule/schedule.js.Schedule.initialize (schedule.js:212)
    at Schedule.webpackJsonp.../../../../primeng/components/schedule/schedule.js.Schedule.ngAfterViewChecked (schedule.js:194)
    at callProviderLifecycles (core.es5.js:11179)
    at callElementProvidersLifecycles (core.es5.js:11147)
    at callLifecycleHooksChildrenFirst (core.es5.js:11131)
    at checkAndUpdateView (core.es5.js:12259)
    at callViewAction (core.es5.js:12599)
    at execComponentViewsAction (core.es5.js:12531)
    at checkAndUpdateView (core.es5.js:12257)
    at callViewAction (core.es5.js:12599)

package.json dependencies

    "dependencies": {
        "@angular/animations": "^4.1.2",
        "@angular/common": "^4.0.0",
        "@angular/compiler": "^4.0.0",
        "@angular/core": "^4.0.0",
        "@angular/forms": "^4.4.7",
        "@angular/http": "^4.0.0",
        "@angular/platform-browser": "^4.0.0",
        "@angular/platform-browser-dynamic": "^4.0.0",
        "@angular/router": "^4.0.0",
        "@types/sprintf": "^0.1.0",
        "ap-angular2-fullcalendar": "^1.2.8",
        "chart.js": "^2.7.1",
        "core-js": "^2.4.1",
        "fullcalendar": "^3.10.1",
        "intl": "^1.2.5",
        "jquery": "^3.5.1",
        "moment": "^2.18.1",
        "ng2-charts": "^1.6.0",
        "ng2-translate": "^5.0.0",
        "node-sass": "^4.13.1",
        "primeng": "^4.0.0",
        "q": "^1.5.1",
        "rxjs": "^5.1.0",
        "sprintf-js": "^1.1.1",
        "zone.js": "^0.8.4"
    },

**Comment by jonathanray** [comment]
**Quick fix**: After upgrading, delete the new `"dependencies": { ... }` object that gets created under `"fullcalendar"` in your `package-lock.json` file.

I ran into the same problem using AngularJS and angular-ui-calendar and did some investigating. The function is being assigned to an instance of jQuery instead of the global jQuery object. I determined this easily by inserting `console.log($ === window.$)` into dist/fullcalendar.js right before the function is assigned to `$.fn.fullCalendar`. I noticed a lot of dependencies were added in my package-lock.json file after upgrading from 3.10.1 to 3.10.2. I deleted the new dependencies object and rebuilt (using browserify) and now it is working. I looks like the new `npm-shrinkwrap.json` adds the dependencies and causes a conflict.

**Comment by acerix** [comment]
If there is still an issue, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the error. Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by willpower232** [comment]
If you have the problem that "fullCalendar is not a function", have updated from 3.10.1 to 3.10.2, find this issue and think you can trivially edit your package-lock.json then think again. Remaking your calendar is the only way.

![image (2)](https://user-images.githubusercontent.com/1619102/85997766-d3d66c00-ba01-11ea-94e6-b7e92579ca4b.png)

**Comment by kevinfairclough** [comment]
npm-shrinkwrap.json should not have been published in this version
